---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ['forwarded_port', {guest: 3000, host: 3000, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver_config:
      box: sendgrid_centos-6_chef-11
      box_url: http://repo.sjc1.sendgrid.net/images/vagrant/metadata/sendgrid_centos-6_chef-11.json

suites:
  - name: default
    run_list:
    - recipe[orchestrator::default]
    - recipe[minitest-handler]
    attributes:
