---

# run the following two commands to test with docker.
# export KITCHEN_YAML=.kitchen.yml
# export KITCHEN_LOCAL_YAML=.kitchen.travis.yml

driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

