---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ['forwarded_port', {guest: 3000, host: 3000, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[orchestrator::default]
    - recipe[minitest-handler]
    attributes:
